# Generated by Django 5.2.1 on 2025-05-17 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_code', models.CharField(max_length=10)),
                ('document_type', models.CharField(max_length=10)),
                ('warehouse_number', models.CharField(blank=True, max_length=5, null=True)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('last_number', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Sekwencja numeracji dokumentów',
                'verbose_name_plural': 'Sekwencje numeracji dokumentów',
                'indexes': [models.Index(fields=['company_code', 'document_type', 'warehouse_number', 'year', 'month'], name='docnum_docu_company_e9a151_idx')],
                'unique_together': {('company_code', 'document_type', 'warehouse_number', 'year', 'month')},
            },
        ),
    ]
