# Generated by Django 5.2 on 2025-04-16 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='Indeks')),
                ('ean', models.CharField(max_length=13, unique=True, verbose_name='EAN')),
                ('name', models.CharField(max_length=255, verbose_name='Nazwa artykułu')),
                ('type', models.CharField(max_length=10, verbose_name='Type')),
                ('unit', models.CharField(default='szt', max_length=10, verbose_name='Jednostka')),
                ('vat_rate', models.CharField(choices=[('0', '0%'), ('5', '5%'), ('8', '8%'), ('23', '23%'), ('NP', 'Nie podlega'), ('ZW', 'Zwolniony')], default='23', max_length=5, verbose_name='Stawka VAT')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktywny')),
            ],
        ),
    ]
