# Generated by Django 5.2 on 2025-04-25 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(
                max_length=1000, null=True, verbose_name='Opis'),
        ),
    ]
