# Generated by Django 5.2.1 on 2025-05-16 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_cn_code_product_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('ND', 'ND'), ('ND-EU', 'ND-EU'), ('D', 'D'), ('V', 'V'), (' ', ' ')], default=' ', max_length=10, verbose_name='Typ rynku'),
        ),
    ]
