# Generated by Django 5.2 on 2025-05-04 19:23

import django.core.validators
import django.db.models.deletion
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscriber', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data aktualizacji')),
                ('country', django_countries.fields.CountryField(help_text='Choose country, to specify a method of VAT number verification', max_length=2, verbose_name='Kraj')),
                ('vat_number', models.CharField(help_text='Enter VAT number without country prefix', max_length=20, verbose_name='VAT number')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Company name')),
                ('name_verified', models.BooleanField(default=False, editable=False, verbose_name='Verified Name')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='City')),
                ('street_name', models.CharField(blank=True, max_length=100, verbose_name='Street')),
                ('building_number', models.CharField(blank=True, max_length=100, verbose_name='Building number')),
                ('apartment_number', models.CharField(blank=True, max_length=10, verbose_name='Apartment number')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='Postal code')),
                ('phone_number', models.CharField(blank=True, validators=[django.core.validators.RegexValidator(message="Numer telefonu musi być w formacie: '+999999999'. Dozwolone do 15 cyfr.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone number')),
                ('additional_info', models.CharField(blank=True, max_length=200, null=True, verbose_name='Additional information')),
                ('is_verified', models.BooleanField(default=False, editable=False, verbose_name='Verified')),
                ('verfication_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Verification date')),
                ('verfication_id', models.CharField(blank=True, editable=False, help_text='Unique query ID from government verification API system', max_length=100, null=True, verbose_name='Verification ID')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Utworzony przez')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Zaktualizowany przez')),
            ],
            options={
                'verbose_name': 'Partner',
                'verbose_name_plural': 'Partners',
            },
        ),
        migrations.CreateModel(
            name='PartnerEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data aktualizacji')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Utworzony przez')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='partner.partner')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='subscriber.subscriber')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Zaktualizowany przez')),
            ],
            options={
                'verbose_name': 'Partner Email',
                'verbose_name_plural': 'Partner Emails',
                'unique_together': {('partner', 'subscriber')},
            },
        ),
        migrations.AddField(
            model_name='partner',
            name='subscriber',
            field=models.ManyToManyField(help_text='Max 10 email addresses', related_name='partnered_with', through='partner.PartnerEmail', to='subscriber.subscriber', verbose_name='Email contacts'),
        ),
        migrations.AlterUniqueTogether(
            name='partner',
            unique_together={('country', 'vat_number')},
        ),
    ]
