# Generated by Django 5.2 on 2025-05-05 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='verfication_date',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='verfication_id',
        ),
        migrations.AddField(
            model_name='partner',
            name='verification_date',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Verification date'),
        ),
        migrations.AddField(
            model_name='partner',
            name='verification_id',
            field=models.CharField(blank=True, editable=False, help_text='Unique query ID from government verification API system', max_length=100, null=True, verbose_name='Verification ID'),
        ),
    ]
