# Generated by Django 5.2 on 2025-05-05 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0002_remove_partner_verfication_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partner',
            old_name='verification_date',
            new_name='veraification_date',
        ),
        migrations.RenameField(
            model_name='partner',
            old_name='verification_id',
            new_name='veraification_id',
        ),
    ]
