# Generated by Django 5.2 on 2025-05-05 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0003_rename_verification_date_partner_veraification_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partner',
            old_name='veraification_date',
            new_name='verification_date',
        ),
        migrations.RenameField(
            model_name='partner',
            old_name='veraification_id',
            new_name='verification_id',
        ),
    ]
