# Generated by Django 5.2 on 2025-05-05 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0004_rename_veraification_date_partner_verification_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='apartment_number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Apartment number'),
        ),
    ]
