# Generated by Django 5.2 on 2025-05-05 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0005_alter_partner_apartment_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='name_verified',
            field=models.BooleanField(default=False, verbose_name='Verified Name'),
        ),
    ]
