# Generated by Django 5.2 on 2025-05-06 09:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0006_alter_partner_name_verified'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VATVerificationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data aktualizacji')),
                ('verification_date', models.DateTimeField(auto_now_add=True, verbose_name='Data weryfikacji')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Zweryfikowany')),
                ('verification_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID weryfikacji')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Wiadomość')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Utworzony przez')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vat_verification_history', to='partner.partner')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Zaktualizowany przez')),
            ],
            options={
                'verbose_name': 'Historia weryfikacji VAT',
                'verbose_name_plural': 'Historie weryfikacji VAT',
                'ordering': ['-verification_date'],
            },
        ),
    ]
