# Generated by Django 5.2.1 on 2025-05-17 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0007_vatverificationhistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partner',
            options={'verbose_name': 'Kontrahent', 'verbose_name_plural': 'Kontrahenci'},
        ),
        migrations.AlterModelOptions(
            name='partneremail',
            options={'verbose_name': 'Email kontrahenta', 'verbose_name_plural': 'Emaile kontrahenta'},
        ),
    ]
