# Generated by Django 5.2.1 on 2025-05-17 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0008_alter_partner_options_alter_partneremail_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktywny'),
        ),
        migrations.AddField(
            model_name='partneremail',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktywny'),
        ),
        migrations.AddField(
            model_name='vatverificationhistory',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktywny'),
        ),
    ]
