# Generated by Django 5.2 on 2025-04-25 10:41

import apps.core.validators
import apps.company.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_userprofile_default_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='krs',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(
                message='Pole moe zawierać tylko cyfry.', regex='^\\d+$'), apps.core.validators.krs_validator]),
        ),
        migrations.AlterField(
            model_name='company',
            name='regon',
            field=models.CharField(max_length=9, unique=True, validators=[django.core.validators.RegexValidator(
                message='Pole moe zawierać tylko cyfry.', regex='^\\d+$'), apps.core.validators.validate_regon]),
        ),
        migrations.AlterField(
            model_name='company',
            name='tax_id',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(
                message='Pole moe zawierać tylko cyfry.', regex='^\\d+$'), apps.core.validators.validate_nip]),
        ),
    ]
