# Generated by Django 5.2 on 2025-05-04 06:17

import apps.core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_company_krs_alter_company_regon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='krs',
            field=models.CharField(unique=True, validators=[django.core.validators.RegexValidator(code='invalid_krs', message='KRS musi składać się z 10 cyfr.', regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='company',
            name='post_code',
            field=models.CharField(validators=[apps.core.validators.validate_postal_code]),
        ),
        migrations.AlterField(
            model_name='company',
            name='regon',
            field=models.CharField(unique=True, validators=[apps.core.validators.validate_regon]),
        ),
        migrations.AlterField(
            model_name='company',
            name='tax_id',
            field=models.CharField(unique=True, validators=[apps.core.validators.validate_nip]),
        ),
    ]
