# Generated by Django 5.2 on 2025-05-04 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_alter_company_krs_alter_company_post_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['name'], 'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['user'], 'verbose_name': 'User profile', 'verbose_name_plural': 'User profiles'},
        ),
    ]
