# Generated by Django 5.2.1 on 2025-05-17 16:23

import apps.core.validators
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_alter_company_options_alter_userprofile_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['name'], 'verbose_name': 'Firma', 'verbose_name_plural': 'Firmy'},
        ),
        migrations.AddField(
            model_name='company',
            name='code',
            field=models.CharField(default='-', help_text='Kod używany w numeracji dokumentów (np. ABC, XYZ)', max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9]+$', 'Kod może zawierać tylko litery i cyfry')], verbose_name='Kod firmy'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='appartment_number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Numer lokalu'),
        ),
        migrations.AlterField(
            model_name='company',
            name='building_number',
            field=models.CharField(max_length=10, verbose_name='Numer budynku'),
        ),
        migrations.AlterField(
            model_name='company',
            name='city',
            field=models.CharField(max_length=50, verbose_name='Miasto'),
        ),
        migrations.AlterField(
            model_name='company',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktywny'),
        ),
        migrations.AlterField(
            model_name='company',
            name='krs',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_krs', message='KRS musi składać się z 10 cyfr.', regex='^\\d{10}$')], verbose_name='KRS'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nazwa'),
        ),
        migrations.AlterField(
            model_name='company',
            name='post_code',
            field=models.CharField(max_length=6, validators=[apps.core.validators.validate_postal_code], verbose_name='Kod pocztowy'),
        ),
        migrations.AlterField(
            model_name='company',
            name='regon',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True, validators=[apps.core.validators.validate_regon], verbose_name='REGON'),
        ),
        migrations.AlterField(
            model_name='company',
            name='street_name',
            field=models.CharField(max_length=50, verbose_name='Ulica'),
        ),
        migrations.AlterField(
            model_name='company',
            name='tax_id',
            field=models.CharField(max_length=10, unique=True, validators=[apps.core.validators.validate_nip], verbose_name='NIP'),
        ),
        migrations.AlterField(
            model_name='company',
            name='tax_id_prefix',
            field=models.CharField(default='PL', max_length=2, verbose_name='Prefiks NIP'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='active_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_users', to='company.company', verbose_name='Aktywna firma'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='company',
            field=models.ManyToManyField(related_name='users', to='company.company', verbose_name='Firmy'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='default_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_users', to='company.company', verbose_name='Domyślna firma'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik'),
        ),
    ]
