# Generated by Django 5.2 on 2025-05-09 10:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscriber', '0002_subscriber_common_name_alter_subscriber_first_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data aktualizacji')),
                ('name', models.CharField(max_length=100, verbose_name='Template name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('html_content', models.TextField(verbose_name='HTML content')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Utworzony przez')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Zaktualizowany przez')),
            ],
            options={
                'verbose_name': 'Newsletter template',
                'verbose_name_plural': 'Newsletter templates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data aktualizacji')),
                ('subject', models.CharField(max_length=255, verbose_name='Subject')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug')),
                ('content', models.TextField(verbose_name='Content')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed')], default='draft', max_length=20, verbose_name='Status')),
                ('scheduled_date', models.DateTimeField(blank=True, null=True, verbose_name='Scheduled date')),
                ('sent_date', models.DateTimeField(blank=True, null=True, verbose_name='Sent date')),
                ('total_recipients', models.IntegerField(default=0, verbose_name='Total recipients')),
                ('open_count', models.IntegerField(default=0, verbose_name='Open count')),
                ('click_count', models.IntegerField(default=0, verbose_name='Click count')),
                ('tracking_id', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Tracking ID')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Utworzony przez')),
                ('subscriber_groups', models.ManyToManyField(blank=True, related_name='received_newsletters', to='subscriber.subscribergroup', verbose_name='Subscriber groups')),
                ('subscribers', models.ManyToManyField(blank=True, related_name='received_newsletters', to='subscriber.subscriber', verbose_name='Subscribers')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Zaktualizowany przez')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='newsletters', to='newsletter.newslettertemplate', verbose_name='Template')),
            ],
            options={
                'verbose_name': 'Newsletter',
                'verbose_name_plural': 'Newsletters',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data aktualizacji')),
                ('event_type', models.CharField(choices=[('open', 'Open'), ('click', 'Click')], max_length=10, verbose_name='Event type')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User agent')),
                ('link_url', models.URLField(blank=True, null=True, verbose_name='Link URL')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Utworzony przez')),
                ('newsletter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_events', to='newsletter.newsletter', verbose_name='Newsletter')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newsletter_events', to='subscriber.subscriber', verbose_name='Subscriber')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Zaktualizowany przez')),
            ],
            options={
                'verbose_name': 'Newsletter tracking',
                'verbose_name_plural': 'Newsletter tracking',
                'ordering': ['-created_at'],
            },
        ),
    ]
