# Generated by Django 5.2.1 on 2025-05-14 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletter',
            options={},
        ),
        migrations.AddField(
            model_name='newsletter',
            name='use_uuid',
            field=models.BooleanField(default=True, verbose_name='Dodaj unikalne identyfikatory'),
        ),
    ]
