# Generated by Django 5.2.1 on 2025-05-14 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_alter_newsletter_options_newsletter_use_uuid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletter',
            options={'ordering': ['-created_at'], 'verbose_name': 'Newsletter', 'verbose_name_plural': 'Newsletters'},
        ),
        migrations.AddField(
            model_name='newslettertracking',
            name='action',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Action'),
        ),
        migrations.AddField(
            model_name='newslettertracking',
            name='tracking_id',
            field=models.UUIDField(blank=True, null=True, verbose_name='Tracking ID'),
        ),
    ]
