# Generated by Django 5.2.1 on 2025-05-17 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0003_alter_newsletter_options_newslettertracking_action_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletter',
            options={},
        ),
        migrations.AlterModelOptions(
            name='newslettertemplate',
            options={'ordering': ['-created_at'], 'verbose_name': 'Szablon newslettera', 'verbose_name_plural': 'Szablony newsletterów'},
        ),
        migrations.AlterModelOptions(
            name='newslettertracking',
            options={'ordering': ['-created_at'], 'verbose_name': 'Tracking newslettera', 'verbose_name_plural': 'Tracking newsletterów'},
        ),
    ]
