# Generated by Django 5.2 on 2025-05-07 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriber', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='common_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Common name'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Last name'),
        ),
    ]
