# Generated by Django 5.2.1 on 2025-05-17 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriber', '0002_subscriber_common_name_alter_subscriber_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriber',
            options={'ordering': ['email'], 'verbose_name': 'Subskrybent', 'verbose_name_plural': 'Subskrybenci'},
        ),
        migrations.AlterModelOptions(
            name='subscribergroup',
            options={'verbose_name': 'Grupa subskrybenta', 'verbose_name_plural': 'Grupy subskrybentów'},
        ),
    ]
