# Generated by Django 5.2.1 on 2025-05-17 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriber', '0003_alter_subscriber_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktywny'),
        ),
        migrations.AddField(
            model_name='subscribergroup',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktywny'),
        ),
    ]
